# -*- coding: utf-8 -*-
"""Copy of Map New IMF to Old IMF_BOL

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DgcXLf0n2qmHBaOYoBlmg_O2pCF26B9b
"""

import pandas as pd
import glob, shutil

print('Running prep_imf_New25...')

#from google.colab import auth
#import gspread
#from google.auth import default
#from googleapiclient.discovery import build

#from google.colab import drive
#drive.mount('/content/drive/')


data_path= './data/imf/raw/'
output_path = './outputs/imf/'


file = glob.glob(data_path+'*')
#file_list = glob.glob(data_path+'/imf/raw/*')
#file name split
file_name = file[0].split('\\')[1].split('.')[0]
df_imf_new =pd.read_csv(file[0])
#print(df_imf.columns.tolist())
# Print the first element of the file list
#print(file[0])
# Print only the extracted file name
print(f"Reading file: {file_name}")
#print(file_list)

#df_imf_new.columns

#Filtering for Type of Transformation, Index Type, and Frequency

df_imf_new=df_imf_new[df_imf_new .TYPE_OF_TRANSFORMATION=='Period average, Year-over-year (YOY) percent change']

df_imf_new=df_imf_new[df_imf_new .INDEX_TYPE=='Consumer price index (CPI)']

df_imf_new=df_imf_new[df_imf_new .FREQUENCY=='Monthly']

#Renaming columns to match the new dataset with the old dataset column headings.

df_imf_new = df_imf_new.rename(columns={'COUNTRY':'Country Name'})

df_imf_new = df_imf_new.rename(columns={'COICOP_1999':'Indicator.Name'})

#df_imf_new.columns
#print(df_imf_new['Indicator.Name'].unique())

#The df_imf_new cpi download does not have a Country Code column. The codes can can be extracted from the first 3 characters of the  SERIES_CODE column. ie AGO is the country code for Angola and is the first 3 characters of AGO.CPI._T.YOY_PCH_PA_PT.M.  The new column should be called "iso_code", This is because later script uses "Country Code" for numeric IMF Country Code, such as 614 for Angola.

df_imf_new['iso_code'] = df_imf_new['SERIES_CODE'].str[:3]

#The df_imf_new cpi download does not have an Indicator Code column. This can be added by associating the Indicator name, in df_imf_new,  with the Indicator Name in the codelist_n.csv file, which is in the data path, and then to add the Indicator Code from codelist_n.csv to the newly created Indicator Code in  df_imf_new.

#  'codelist_n.csv' is in the data_path and has 'Indicator Name' and 'Indicator Code' columns
#codelist_path =  '.data/codelist_n.csv'
#df_codelist = pd.read_csv(codelist_path, sep=';')
df_codelist = pd.read_csv('./data/codeList_n.csv', sep=';')

# Load the codelist CSV into a DataFrame
#try:
#   df_codelist = pd.read_csv(codelist_path, sep=';')
#   print(f"Successfully loaded codelist from: {codelist_path}")
#except FileNotFoundError:
#   print(f"Error: codelist file not found at {codelist_path}")
   # error can be handled more robustly, e.g., exit or raise an exception
#   exit()


# Perform the merge operation
#  use a left merge to keep all rows from df_imf_new
# merge on the 'Indicator Name' column
# The 'Indicator Code' column will be added from df_codelist
df_imf_new = pd.merge(df_imf_new, df_codelist[['Indicator.Name', 'Indicator.Code']], on='Indicator.Name', how='left')

# print the first few rows of the updated DataFrame to verify
#print("\nDataFrame after adding 'Indicator.Code':")
#df_imf_new.info()
#print(df_imf_new.head())

# Check if the 'Indicator Code' column was added and if there are any missing values
#print("\nInfo about the updated DataFrame:")
#df_imf_new.info()

#df_imf_new.columns

#print(df_imf_new['Indicator.Code'].unique())

# Identify rows where 'Indicator.Code' is NaN
#rows_with_nan_code = df_imf_new[df_imf_new['Indicator.Code'].isna()]

# Get the unique 'Indicator.Name' values from these rows
#indicator_names_with_nan_code = rows_with_nan_code['Indicator.Name'].unique()

#print("\n'Indicator.Name' values that resulted in NaN 'Indicator.Code':")
#print(indicator_names_with_nan_code)

#"""*   Replace 'All Items'  in the 'Indicator.Name' column of your df_imf_new DataFrame with 'Consumer Price Index, All items' List item
#*  diff: Housing, water, electricity, gas and other fuels != Housing, Water, Electricity, Gas and Other Fuels
#*   diff: Alcoholic beverages, tobacco and narcotics != Alcoholic Beverages, Tobacco, and Narcotics"""

df_imf_new['Indicator.Name'] = df_imf_new['Indicator.Name'].replace('All Items', 'Consumer Price Index, All items')

#print(df_imf_new['Indicator.Name'].unique())

df_imf_new['Indicator.Name'] = df_imf_new['Indicator.Name'].replace({'Housing, water, electricity, gas and other fuels': 'Housing, Water, Electricity, Gas and Other Fuels','Alcoholic beverages, tobacco and narcotics': 'Alcoholic Beverages, Tobacco, and Narcotics'})
#print(df_imf_new['Indicator.Name'].unique())

#Remove the hyphens and leading zeros from the column headings of  DataFrame df_imf_new
# Get the current list of column names
current_cols = df_imf_new.columns

# Create a new list of column names with hyphens and leading zeros in month codes
# removed
new_cols = []
for col in current_cols:
    modified_col = col.replace('-', '') # Remove hyphens first

    # Replace 'M01' with 'M1', 'M02' with 'M2', etc. up to 'M09' with 'M9'
    for i in range(1, 10):
        old_month_code = f'M0{i}'
        new_month_code = f'M{i}'
        modified_col = modified_col.replace(old_month_code, new_month_code)

    new_cols.append(modified_col)

# Assign the new list of column names back to the DataFrame
df_imf_new.columns = new_cols

# print the updated column names to verify
#print("Updated DataFrame column names:")
#print(df_imf_new.columns)
#df_imf_new.info()
#print(df_imf_new.head())

#"""The df_imf_new cpi download does not have an IMFCountry Code column. This can be added by associating the iso_code, in df_imf_new, with the iso_code in the imf_country_codes.csv file, which is in the data path, and then to add the imf_code from codelist_n.csv to the  df_imf_new."""

# The code below adds imf_code, which are country numeric codes, to df_imf_new
#  'imf_country_codes.csv' is in data_path and has 'imf_code', 'iso_code' and 'country' columns
#imf_code,iso_code,country
#512,AFG,Afghanistan
#The join must be on iso_code in  'imf_country_codes.csv'  and df_imf_new

iso_code_path = ('./data/imf/imf_country_codes.csv')


# Load the codelist CSV into a DataFrame
#try:
df_iso_code = pd.read_csv(iso_code_path, sep=',')
print(f"Successfully loaded'imf_country_codes.csv from: {iso_code_path}")
#except FileNotFoundError:
#    print(f"Error: 'imf_country_codes.csv file not found at {iso_code_path}")
    # You might want to handle this error more robustly, e.g., exit or raise an exception
#    exit()


# Perform the merge operation
# Use a left merge to keep all rows from df_imf_new
# Merge on the 'iso_code' column
# The 'imf_code' column will be added from df_iso_code
df_imf_new = pd.merge(df_imf_new, df_iso_code[['iso_code', 'imf_code']], on='iso_code', how='left')

# print the first few rows of the updated DataFrame to verify
#print("\nDataFrame after adding 'imf_code':")
#df_imf_new.info()
#print(df_imf_new.head())

# Check if the 'imf_code' column was added and if there are any missing values
#print("\nInfo about the updated DataFrame:")
#df_imf_new.info()

# Convert the 'imf_code' column to integer type
# Use errors='coerce' to turn any values that cannot be converted into NaN
# Then, use nullable_int to handle potential NaN values after conversion
df_imf_new['imf_code'] = df_imf_new['imf_code'].astype(pd.Int64Dtype())

# print the info and head to verify the change
#print("\nDataFrame after converting 'imf_code' to integer:")
#df_imf_new.info()
#print(df_imf_new.head())

#"""**Select only the rows for African countries**The legacy download had a "Country Code" column, which for example, had the IMF code of 612 for  Algeria.  The new download file has a "iso_code" column added and has an alphabetic code, such as, DZA for Algeria. df_imf_new has had 'imf_code' added and has 3 character integers, such as 111A new column for the IMF code will need to added to the new  download and should be called "Country Code".  This should be added from imf_country_codes.csv. in this join iso_code from imf_country_codes.csv = iso_code column added to the new df_imf_new by subsequent code.  The join is on iso_code and the new column is Country Code. Resulted in zero rows.Add the imf code for all countries before filtering for the African Countries"""

#Filtering for african countries, filter df_imf_new based on the ISO codes that
#correspond to African countries, not the IMF numeric codes.
#imf_code does exist in df_imf_new, it is 3 digits, ie, 111
#imf_code exists in  map_imf_iso_code.csv ie, 3 digits, 111

# Load the mapping file ('./data/imf/imf_country_codes.csv')
#iso_codes_map = pd.read_csv(data_path+'/imf/map_imf_iso_code.csv')
iso_codes_map = pd.read_csv('./data/imf/map_imf_iso_code.csv')
# Get the list of ISO codes for African countries
african_iso_codes = iso_codes_map['iso_code'].drop_duplicates().to_list()

# Filter df_imf_new to keep only rows where the 'iso_code' is in the list of African ISO codes
# Use .copy() to avoid SettingWithCopyWarning
df_imf_new_african = df_imf_new[df_imf_new['iso_code'].isin(african_iso_codes)].copy()

# Before merging the new 'Country Code', drop the existing 'imf_code' column
# This avoids the column name conflict during the merge
if 'imf_code' in df_imf_new_african.columns:
    df_imf_new_african = df_imf_new_african.drop(columns=['imf_code'])


# Now merge to add the 'Country Code' (IMF numeric code)
# Ensure the iso_codes_map has the columns needed for merging ('iso_code', 'imf_code')
# Rename 'imf_code' to 'Country Code' in the map for merging
iso_codes_for_merge = iso_codes_map.rename(columns={'imf_code':'Country Code'})[['iso_code', 'Country Code']]

# Perform the merge
df_imf_new_african = pd.merge(df_imf_new_african, iso_codes_for_merge, how='left', on='iso_code')

# Update df_imf_new to be the filtered African data
df_imf_new = df_imf_new_african

countries_imf_af = df_imf_new['Country Name'].drop_duplicates().to_list()
#df_imf_new.info()
#print(df_imf_new.head())

#To drop duplicates based on all columns:
df_imf_new_cleaned = df_imf_new.drop_duplicates()
#df_imf_new_cleaned.info()
# Corrected print and save lines to use df_imf_new_cleaned
# print(df_imf_new_cleaned.head())

#print(f"\nNumber of rows after dropping all duplicates: {len(df_imf_new_cleaned)}")


# output_path for df_imf_new is defined from your previous code
#output_excel_path = output_path + '/df_imf_new_cleaned.xlsx'

# Save the DataFrame to an Excel file
#df_imf_new_cleaned.to_excel(output_excel_path, index=False)

#print(f"DataFrame saved to {output_excel_path}")

df_imf_new_cleaned = df_imf_new_cleaned.rename(columns={'Country Code_x':'Country Code', 'Country Name':'Country'})

df_imf_new_cleaned['Attribute'] = 'Value'

df_imf_new_cleaned.info()
# print to view rename in df_imf_new_cleaned
#print(df_imf_new_cleaned.head())

"""Drop columns"""

cols_to_keep_fixed = ['Country', 'Indicator.Name', 'Indicator.Code','Attribute']

import re

# Function to check if a column name is a date column and is 2008M1 or later
def is_date_col_2008_onwards(col_name):
    match = re.match(r'(\d{4})M(\d{1,2})', col_name)
    if match:
        year = int(match.group(1))
        month = int(match.group(2))
        # Consider months from 2008M1 onwards
        return year > 2008 or (year == 2008 and month >= 1)
    return False

# Get all column names from your DataFrame
all_cols = df_imf_new_cleaned.columns.tolist()

# Filter for date columns from 2008M1 onwards
date_cols_to_keep = [col for col in all_cols if is_date_col_2008_onwards(col)]

# Combine the fixed columns and the date columns
all_cols_to_keep = cols_to_keep_fixed + date_cols_to_keep

# Reindex the DataFrame to keep only the specified columns
df_imf_filtered = df_imf_new_cleaned[all_cols_to_keep]

# print the info and head of the new DataFrame to verify
#print("\nDataFrame after filtering columns:")
#df_imf_filtered.info()
#print(df_imf_filtered.head())

#"""'''# here are the new country names that need to be fixed:
#Comoros, Union of the = Comoros
#Congo, Democratic Republic of the = Democratic Republic of the Congo
#Congo, Republic of
#Egypt, Arab Republic of
#Equatorial Guinea, Republic of
#Eswatini, Kingdom of
#Ethiopia, The Federal Democratic Republic of
#Gambia, The
#Lesotho, Kingdom of
#Madagascar, Republic of
#Mauritania, Islamic Republic of
#Mozambique, Republic of
#São Tomé and Príncipe, Democratic Republic of
#South Sudan, Republic of
#Tanzania, United Republic of
#'''"""

# Define the mapping of old country names to new country names
country_name_mapping = {'Comoros, Union of the': 'Comoros',    'Congo, Democratic Republic of the': 'Democratic Republic of the Congo',    'Congo, Republic of': 'Republic of Congo','Egypt, Arab Republic of': 'Egypt','Equatorial Guinea, Republic of': 'Equatorial Guinea', 'Eswatini, Kingdom of': 'Eswatini', 'Ethiopia, The Federal Democratic Republic of': 'Ethiopia', 'Gambia, The': 'The Gambia', 'Lesotho, Kingdom of': 'Lesotho', 'Madagascar, Republic of': 'Madagascar', 'Mauritania, Islamic Republic of': 'Mauritania', 'Mozambique, Republic of': 'Mozambique', 'São Tomé and Príncipe, Democratic Republic of': 'São Tomé and Príncipe', 'South Sudan, Republic of': 'South Sudan', 'Tanzania, United Republic of': 'Tanzania'}

# Replace the country names in the 'Country' column
df_imf_filtered['Country'] = df_imf_filtered['Country'].replace(country_name_mapping)

# print the unique values in the 'Country' column to verify the changes
#print("Unique country names after renaming:")
#print(df_imf_filtered['Country'].unique())

# print the first few rows of the updated DataFrame
#print(df_imf_filtered.head())


#move old output files to backup

output_path = './outputs/imf/'
files = glob.glob(output_path+'*.xlsx')
for file in files:
    shutil.move(file,'./outputs/imf/bk/')

#"""Rename File Name
#Save df_imf_filtered as an xlsx file with a naming format similar to CPI_06-17-2025 07-53-18-71_timeSeries_africa, which is the legacy file name structure. Except that the new file name format is dataset_2025-04-07T08_31_52.572084672Z_DEFAULT_INTEGRATION_IMF.STA_CPI_3.0.1.csv
#"""

# Add the code here to save df_imf_filtered
import re
from datetime import datetime

# Assuming 'file_name' is already extracted from the input file path
# and is something like 'dataset_2025-04-07T08_31_52.572084672Z_DEFAULT_INTEGRATION_IMF.STA_CPI_3.0.1.csv'
# If not, you'll need to adapt this part to get the raw filename string

# Example raw_filename (replace with your actual 'file_name' if needed)
raw_filename = file_name.split('.')[0] # Remove the extension if present

# Extract the date and time part from the raw filename
# The pattern looks for 'YYYY-MM-DDTHH_MM_SS' after 'dataset_'
match = re.search(r'dataset_(\d{4}-\d{2}-\d{2}T\d{2}_\d{2}_\d{2})', raw_filename)

if match:
    # Extracted date string in the format 'YYYY-MM-DDTHH_MM_SS'
    date_str = match.group(1)

    # Parse the extracted date string into a datetime object
    # Replace '_' with ':' for parsing
    date_obj = datetime.strptime(date_str.replace('_', ':'), '%Y-%m-%dT%H:%M:%S')

    # Format the datetime object into the desired output format 'MM-DD-YYYY HH-MM-SS'
    formatted_date = date_obj.strftime('%m-%d-%Y %H-%M-%S')

    # Construct the new filename
    new_filename = f'CPI_{formatted_date}_NewtimeSeries_africa.xlsx'

    # Define the full output path
    output_excel_path = f'{output_path}/{new_filename}'

    # Save the DataFrame to an Excel file
    df_imf_filtered.to_excel(output_excel_path, index=False)

    #print(f"DataFrame saved to {output_excel_path}")

else:
    print(f"Could not extract date from filename: {raw_filename}. Using default filename.")
    # Fallback to a default filename if date extraction fails
    output_excel_path = output_path + '/df_imf_filtered.xlsx'
    df_imf_filtered.to_excel(output_excel_path, index=False)
    #print(f"DataFrame saved to {output_excel_path}")

