# -*- coding: utf-8 -*-
"""Copy of adh_prep_gambia25xl.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t6QnVxD2mQ4E1q6KU_emW9wtTPxaCuE8

-*- coding: utf-8 -*-
'''
Created on Mon Sep 19 13:37:30 2022

@author: heiko

import tabula
import pandas as pd
from datetime import datetime, timedelta
import glob, shutil
import re, os
'''
"""

import pandas as pd
import glob
from datetime import datetime, timedelta
from pathlib import Path
import re, os
#from google.colab import drive
#from google.colab import data_table
#data_table.enable_dataframe_formatter()
#drive.mount('/content/drive/')

data_path = './data/gambia/raw/'
out_path = './data/gambia/csv/'
data_path2 = './outputs/ckan/bk/template.csv'

import os
#print(os.listdir(data_path))
#print(os.listdir(out_path))

# functions and definitions

def get_last_date_of_month(year, month):
    """Return the last date of the month.

    Args:
        year (int): Year, i.e. 2022
        month (int): Month, i.e. 1 for January

    Returns:
        date (datetime): Last date of the current month
    """

    if month == 12:
        last_date = datetime(year, month, 31)
    else:
        last_date = datetime(year, month + 1, 1) + timedelta(days=-1)

    return last_date.strftime("%Y-%m-%d")


months = dict({'Jan':1,
               'Feb':2,
               'Mar':3,
               'Apr':4,
               'May':5,
               'Jun':6,
               'Jul':7,
               'Aug':8,
               'Sep':9,
               'Oct':10,
               'Nov':11,
               'Dec':12
               })

def mapp_values(df,template):
    # Work on a copy to avoid SettingWithCopyWarning
    df_copy = df.copy()
    template = template.loc[:,['Indicator.Name','Indicator.Code']]
    # find a word that is common to template and dataset
    values = ['All',
              'Food ',
              'Tobacco',
              'Clothing',
              'Communication',
              'Education',
              'Housing',
              'Household',
              'Health',
              'Miscellaneous',
              'Recreation',
              'Restaurant',
              'Transport',
              'Insurance']

    for i in range(len(values)):
        # Find matching rows in template
        val_template = template[template['Indicator.Name'].str.contains(values[i],case=False, na=False)==True]
        # Find matching rows in the dataframe copy
        mask_df = df_copy['Indicator.Name'].str.contains(values[i],case=False, na=False)==True

        if not val_template.empty and mask_df.any():
            try:
                # Assign the Indicator.Name from the template to the matching rows in the copy
                df_copy.loc[mask_df, 'Indicator.Name'] = val_template['Indicator.Name'].values[0]
            except Exception as e:
                print(f'ERROR assigning value for: {values[i]} - {e}')
        else:
             print(f'WARNING: No match found in template or dataframe for: {values[i]}')

    # Merge with template to get Indicator.Code
    df_merged = pd.merge(template,df_copy,how='left',on = 'Indicator.Name')
    df_merged = df_merged.round(2)
    return df_merged

def execute(data_path, country):
    #codes = pd.read_csv('./data/codeList.csv')
    # get template
    if '_' in country:
        c = country.split('_')
        c = [i.capitalize() for i in c]
        country2 = ' '.join(c)
    else:
        country2 = country.capitalize()


 #month = [val for key, val in months.items() if key.lower() in data_path][0]
    month = data_path.split('/')[4][8:11]
    month = months[month.lower().capitalize()]
    year = re.search(r'.*([1-3][0-9]{3})',data_path).group(1) # [1-3] = num between 1-3, [0-9]{3} = num 0-9 repeat 3 times
    year = int(year)
    last = get_last_date_of_month(year, month)


sheet_name = "NChained Link Series to Publish"

# Define the output directory and CSV file name
output_directory = out_path

# Define the original 1-indexed row numbers to keep for CPI calculation
# These rows will be adjusted to 0-indexed after initial DataFrame cleaning
rows_to_keep_original_indices = [14, 15, 28, 31, 37, 41, 46, 47, 48, 49, 52, 53, 54]


#%%
def template(country):
    #codes = pd.read_csv('./data/codeList.csv')
    # get template
    if '_' in country:
        c = country.split('_')
        c = [i.capitalize() for i in c]
        country2 = ' '.join(c)
    else:
        country2 = country.capitalize()
    file = './outputs/ckan/bk/template.csv'
    df_template = pd.read_csv(file)
    df_template = df_template[df_template['Country']==country2]
    #df_template = df_template.iloc[:,[0,1,2,3,4,-2,-1]]

    # save this in csv folder
    csv_folder = './data/%s/csv/'% country
    df_template.to_csv('{}{}_template.csv'.format(csv_folder,country),index=False)

#template(country)

# get template

file = data_path2
df_template = pd.read_csv(file)
country2 = 'The Gambia' # Define country2 here
# Print unique country names in the template before filtering
#print("Unique country names in template before filtering:")
#print(df_template['Country'].unique())

df_template = df_template[df_template['Country']==country2]
df_template = df_template.iloc[:,[0,1,2,3,4,-2,-1]]
df_template = df_template[df_template['Indicator.Name']!='Insurance and Financial Services']
# map all items
#df_1 = mapp_values(df_inflation,df_template)

country = 'gambia' # Define country here
# save this in csv folder

# Use output_csv_path_mapped for the output file path
#DF!HEREdf_1.to_csv(output_csv_path_mapped,index=False)

#%% check if there are new files
country = 'gambia'
# Use the data_path variable defined earlier which points to the raw data directory
base_data_path = data_path

# files_list = glob.glob('%s*.xlsx'% base_data_path)
# Use pathlib to get the list of excel files
files_list = [str(f) for f in Path(base_data_path).glob('*.xlsx')]

# for i in range(len(files_list)):
#     files_list[i] = files_list[i].replace("//","/")

#%%
#check for data log
#data_log_path = os.path.join(base_data_path, 'data_log.txt')
data_log_path = Path(base_data_path)/'data_log.txt'
# Path(base_data_path)/'data_log.txt'
data_log = []
if data_log_path.exists():
    with open(data_log_path, 'r') as f:
        data_log = [line.strip() for line in f if line.strip()]

files_to_process = [f for f in files_list if f not in data_log]

if not files_to_process:
    print('No new %s country data'% country)
else:
    print('Preparing %s data...'% country)

    # Open the data log file in append mode once before the loop
    with open(data_log_path, 'a') as f:
        for file_path in files_to_process:
            print(f"Processing {file_path}...")

            try:
                # Extract file_name from the file_path being processed
                file_name = Path(file_path).name

                # Define the input Excel file path and sheet name
                input_file_path = Path(file_path)
                sheet_name = "NChained Link Series to Publish"

                # Define the output directory and CSV file name
                output_directory = Path(out_path)
                output_csv_name = file_name.replace(".xlsx", ".csv")
                output_csv_path = output_directory / output_csv_name

                # Define the original 1-indexed row numbers to keep for CPI calculation
                rows_to_keep_original_indices = [14, 15, 28, 31, 37, 41, 46, 47, 48, 49, 52, 53, 54]

                # Ensure the output directory exists
                output_directory.mkdir(parents=True, exist_ok=True)

                # 1. Load the Excel file
                df = pd.read_excel(input_file_path, sheet_name=sheet_name, header=None)

                # 2. Clean the DataFrame
                df = df.iloc[13:].copy()
                indices_to_drop_from_current_df = list(range(43, 49))
                df = df.drop(df.index[indices_to_drop_from_current_df]).copy()
                df.columns = df.iloc[0]
                df = df[1:].copy()
                df = df.iloc[:, 1:].copy()

                # Adjust the row indices to be 0-indexed
                rows_to_keep_new_indices = [idx - 14 for idx in rows_to_keep_original_indices]

                # Select only the specified rows for CPI calculation
                df_selected = df.iloc[rows_to_keep_new_indices].copy()

                # Get column names for CPI calculation
                last_column_name = df_selected.columns[-1]
                twelfth_before_last_column_name = df_selected.columns[-13]

                # Convert columns to numeric type
                df_selected[last_column_name] = pd.to_numeric(df_selected[last_column_name], errors='coerce')
                df_selected[twelfth_before_last_column_name] = pd.to_numeric(df_selected[twelfth_before_last_column_name], errors='coerce')

                # 3. Calculate CPI
                cpi_values = (
                    (df_selected[last_column_name] - df_selected[twelfth_before_last_column_name]) /
                    df_selected[twelfth_before_last_column_name]
                ) * 100

                # 4. Get the indicator names
                indicator_names = df_selected.iloc[:, 1].astype(str).str.strip()

                # 5. Create the df_inflation DataFrame
                df_inflation = pd.DataFrame({
                    "Indicator.Name": indicator_names.values,
                    last_column_name: cpi_values.values
                })

                # 6. Get template and map values
                file = data_path2 # data_path2 is defined globally
                df_template = pd.read_csv(file)
                country2 = 'The Gambia' # Use the correct country name
                df_template = df_template[df_template['Country']==country2]
                df_template = df_template.iloc[:,[0,1,2,3,4,-2,-1]]
                df_template = df_template[df_template['Indicator.Name']!='Insurance and Financial Services']

                # Map all items using the mapp_values function defined in another cell
                df_1 = mapp_values(df_inflation,df_template)

                # 7. Save the result as a CSV file
                df_1.to_csv(output_csv_path, index=False)

                print(f"Successfully processed and saved {file_name} to {output_csv_path}")

                # Write the processed file path to the data log
                #f.write(file_path + '/n')
                # Write the processed file path to the data log - Fixed: Changed '/n' to '\n' for newline
                f.write(str(file_path) + '\n')
                

            except FileNotFoundError:
                print(f"Error: The input file was not found at {file_path}")
            except KeyError as e:
                print(f"Error processing {file_name}: A column or sheet name was not found. Error: {e}")
            except Exception as e:
                print(f"An unexpected error occurred while processing {file_name}: {e}")